### ISSUE TITLE
Question about how to get the future line

### ISSUE THREAD

**Issue by GilgameshD** [zxc-tju/InterHub#1]
Hi,

According to this line https://github.com/zxc-tju/InterHub/blob/main/utils/SceneProcessor.py#L320, the variable additional_trajectory is not used. So my understanding is that the future line is only the future trjectories in `timerange`. Then, the map information is totally ignored during this process. Is this correct?

Best,

**Comment by zxc-tju** [comment]
Hi Wenhao,

Yes, you are correct. This process does not necessarily rely on map information which is totally ignored in the current implementation. The interaction intensity calculation within the `timerange` could work solely with the ground truth trajectory data. While map information could be used to generate `additional_trajectory` to provide dummy future trajectories for calculating interaction intensity near the end of the trajectory segment, it is excluded in the current implementation due to accuracy concerns.

Best，
Xiaocong

**Comment by GilgameshD** [comment]
Thanks for your response!

I have another question about the results. I tried to run the metric on nuplan and nuscenes, but it looks like most of the pairs of vehicles do not have intersections if we only use the gt future. Maybe it's because the `timerange=5` is too short. Then, the final results only have a few valid scenarios while the others are filtered out. Thanks!

**Comment by zxc-tju** [comment]
The number of extracted scenarios is indeed sensitive to the time range considered. The choice of `timerange=5` seconds is somewhat empirical and is limited by the length of the source segments in the raw dataset. However, increasing the time range does not ensure more extracted cases. The key idea behind "interaction intensity" is to measure the effort required to resolve a conflict using the "best" collaborative solution. Thus, given the same initial conflict state, a longer time period can make collaboration easier, reducing the average effort required (which is the metric for interaction intensity). As a result, a longer time window might actually lead to a lower measured interaction intensity.

Hope this helps :)

**Comment by GilgameshD** [comment]
yeah, that makes sense. If I understand correctly, one assumption here is that the interaction intensity is 0 if there is no potential collision in the future?

**Comment by zxc-tju** [comment]
yes that's it
